/* tslint:disable */
/* eslint-disable */
/**
 * esa API v1
 * チームのナレッジ共有サービス[esa.io](https://esa.io/)のAPI v1の仕様書
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { NewEmoji } from "./new-emoji";

/**
 * 新たに登録する絵文字を表します。
 * @export
 * @interface CreateEmojiBody
 */
export interface CreateEmojiBody {
  /**
   *
   * @type {NewEmoji}
   * @memberof CreateEmojiBody
   */
  emoji: NewEmoji;
}
