/* tslint:disable */
/* eslint-disable */
/**
 * esa API v1
 * チームのナレッジ共有サービス[esa.io](https://esa.io/)のAPI v1の仕様書
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 新たに登録された絵文字を表します
 * @export
 * @interface CreatedEmoji
 */
export interface CreatedEmoji {
  /**
   * 絵文字を入力する際に使うコードです
   * @type {string}
   * @memberof CreatedEmoji
   */
  code: string;
}
