/* tslint:disable */
/* eslint-disable */
/**
 * esa API v1
 * チームのナレッジ共有サービス[esa.io](https://esa.io/)のAPI v1の仕様書
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { OriginalRevision } from "./original-revision";

/**
 *
 * @export
 * @interface EditPost
 */
export interface EditPost {
  /**
   * 記事のタイトル  -  タイトル自体に`#`を含めたい場合は`&#35;`, `/`を含めたい場合は`&#47;`へそれぞれ置換処理をお願いします。
   * @type {string}
   * @memberof EditPost
   */
  name?: string;
  /**
   * Markdownで書かれた記事の本文です
   * @type {string}
   * @memberof EditPost
   */
  body_md?: string;
  /**
   * 記事に紐付けられたタグです。
   * @type {Array<string>}
   * @memberof EditPost
   */
  tags?: Array<string>;
  /**
   * 記事が属するカテゴリです  設定されていない場合は`null`になります
   * @type {string}
   * @memberof EditPost
   */
  category?: string | null;
  /**
   * 記事がWIP(Working In Progress)状態かどうかを表します。
   * @type {boolean}
   * @memberof EditPost
   */
  wip?: boolean;
  /**
   * 記事更新時の変更メモです。
   * @type {string}
   * @memberof EditPost
   */
  message?: string;
  /**
   * 記事の投稿者  - チームメンバーのscreen_nameもしくは \"esa_bot\" を指定することで記事の **作成者** を上書きすることができます。 - このパラメータは **team の owner** だけ が使用することができます。
   * @type {string}
   * @memberof EditPost
   */
  created_by?: string;
  /**
   * 記事の更新者  - チームメンバーのscreen_nameもしくは \"esa_bot\" を指定することで記事の **更新者** を上書きすることができます。 - このパラメータは **team の owner** だけ が使用することができます。
   * @type {string}
   * @memberof EditPost
   */
  updated_by?: string;
  /**
   *
   * @type {OriginalRevision}
   * @memberof EditPost
   */
  original_revision?: OriginalRevision;
}
