/* tslint:disable */
/* eslint-disable */
/**
 * esa API v1
 * チームのナレッジ共有サービス[esa.io](https://esa.io/)のAPI v1の仕様書
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 絵文字を表します
 * @export
 * @interface Emoji
 */
export interface Emoji {
  /**
   * 絵文字を入力する際に使うコードです
   * @type {string}
   * @memberof Emoji
   */
  code: string;
  /**
   * 絵文字に対するエイリアスコードです
   * @type {Array<string>}
   * @memberof Emoji
   */
  aliases: Array<string>;
  /**
   * 絵文字のカテゴリです  カスタム絵文字は`Custom`です。
   * @type {string}
   * @memberof Emoji
   */
  category: string;
  /**
   * 絵文字の画像URLです
   * @type {string}
   * @memberof Emoji
   */
  url: string;
}
