/* tslint:disable */
/* eslint-disable */
/**
 * esa API v1
 * チームのナレッジ共有サービス[esa.io](https://esa.io/)のAPI v1の仕様書
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 新たに投稿する記事を表します。
 * @export
 * @interface NewPost
 */
export interface NewPost {
  /**
   * 記事のタイトル  -  タイトル自体に`#`を含めたい場合は`&#35;`, `/`を含めたい場合は`&#47;`へそれぞれ置換処理をお願いします。
   * @type {string}
   * @memberof NewPost
   */
  name: string;
  /**
   * Markdownで書かれた記事の本文です
   * @type {string}
   * @memberof NewPost
   */
  body_md?: string;
  /**
   * 記事に紐付けられたタグです。
   * @type {Array<string>}
   * @memberof NewPost
   */
  tags?: Array<string>;
  /**
   * 記事が属するカテゴリです  設定されていない場合は`null`になります
   * @type {string}
   * @memberof NewPost
   */
  category?: string | null;
  /**
   * 記事がWIP(Working In Progress)状態かどうかを表します。
   * @type {boolean}
   * @memberof NewPost
   */
  wip?: boolean;
  /**
   * 記事更新時の変更メモです。
   * @type {string}
   * @memberof NewPost
   */
  message?: string;
  /**
   * 記事の投稿者  - チームメンバーのscreen_nameもしくは \"esa_bot\" を指定することで記事の投稿者を上書きすることができます。 - このパラメータは **team の owner** だけ が使用することができます。
   * @type {string}
   * @memberof NewPost
   */
  user?: string;
  /**
   * チーム内のテンプレート記事のID(URLのこの部分: /posts/_**{id}**)を指定すると、そのテンプレートが適用された**name**と**body**を持つ記事を作成することが出来ます。
   * @type {number}
   * @memberof NewPost
   */
  template_post_id?: number;
}
