/* tslint:disable */
/* eslint-disable */
/**
 * esa API v1
 * チームのナレッジ共有サービス[esa.io](https://esa.io/)のAPI v1の仕様書
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 新たにStarする内容を表します。
 * @export
 * @interface NewStar
 */
export interface NewStar {
  /**
   * 引用Starの本文です。
   * @type {string}
   * @memberof NewStar
   */
  body?: string;
}
