/* tslint:disable */
/* eslint-disable */
/**
 * esa API v1
 * チームのナレッジ共有サービス[esa.io](https://esa.io/)のAPI v1の仕様書
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface NewComment
 */
export interface NewComment {
  /**
   *
   * @type {string}
   * @memberof NewComment
   */
  body_md: string;
  /**
   * コメントの投稿者  - チームメンバーのscreen_nameもしくは \"esa_bot\" を指定することでコメントの投稿者を上書きすることができます。 - このパラメータは **team の owner** だけ が使用することができます。
   * @type {string}
   * @memberof NewComment
   */
  user?: string;
}
