/* tslint:disable */
/* eslint-disable */
/**
 * esa API v1
 * チームのナレッジ共有サービス[esa.io](https://esa.io/)のAPI v1の仕様書
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * リクエストに正常な `post.body_md` パラメータと `post.original_revision.*` パラメータが存在する場合、記事更新時に3 way mergeが行われます。original_revisionパラメータが存在しない場合は、変更は常に後勝ちになります。  > [release_note/2014/12/23/記事保存時の自動マージ - docs.esa.io](https://docs.esa.io/posts/35)
 * @export
 * @interface OriginalRevision
 */
export interface OriginalRevision {
  /**
   * 変更前の記事の本文です
   * @type {string}
   * @memberof OriginalRevision
   */
  body_md: string;
  /**
   * 変更前の記事のrevision_numberを指定します
   * @type {number}
   * @memberof OriginalRevision
   */
  number: number;
  /**
   * 変更前の記事の最終更新者のscreen_nameを指定します
   * @type {string}
   * @memberof OriginalRevision
   */
  user: string;
}
