/* tslint:disable */
/* eslint-disable */
/**
 * esa API v1
 * チームのナレッジ共有サービス[esa.io](https://esa.io/)のAPI v1の仕様書
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { User } from "./user";

/**
 * 記事にStarをしている人
 * @export
 * @interface Stargazer
 */
export interface Stargazer {
  /**
   * Starをした日時です。
   * @type {string}
   * @memberof Stargazer
   */
  created_at: string;
  /**
   * 引用Starの本文です。
   * @type {string}
   * @memberof Stargazer
   */
  body: string | null;
  /**
   * Starをしたユーザです。
   * @type {User}
   * @memberof Stargazer
   */
  user: User;
}
