/* tslint:disable */
/* eslint-disable */
/**
 * esa API v1
 * チームのナレッジ共有サービス[esa.io](https://esa.io/)のAPI v1の仕様書
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 記事のタグ
 * @export
 * @interface Tag
 */
export interface Tag {
  /**
   * タグ名です。
   * @type {string}
   * @memberof Tag
   */
  name: string;
  /**
   * タグ付けされた記事数です。
   * @type {number}
   * @memberof Tag
   */
  posts_count: number;
}
