/* tslint:disable */
/* eslint-disable */
/**
 * esa API v1
 * チームのナレッジ共有サービス[esa.io](https://esa.io/)のAPI v1の仕様書
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * チームの統計情報を表します。
 * @export
 * @interface TeamStats
 */
export interface TeamStats {
  /**
   * チーム内のメンバーの総数です
   * @type {number}
   * @memberof TeamStats
   */
  members: number;
  /**
   * チーム内の記事の総数です
   * @type {number}
   * @memberof TeamStats
   */
  posts: number;
  /**
   * チーム内の記事(wip)の総数です
   * @type {number}
   * @memberof TeamStats
   */
  posts_wip: number;
  /**
   * チーム内の記事(shipped)の総数です
   * @type {number}
   * @memberof TeamStats
   */
  posts_shipped: number;
  /**
   * チーム内の記事につけられたコメントの総数です
   * @type {number}
   * @memberof TeamStats
   */
  comments: number;
  /**
   * チーム内の記事につけられたスターの総数です
   * @type {number}
   * @memberof TeamStats
   */
  stars: number;
  /**
   * 過去24時間以内に記事の新規投稿/更新・コメント・Star等の活動を行ったメンバー数です。
   * @type {number}
   * @memberof TeamStats
   */
  daily_active_users: number;
  /**
   * 過去7日間以内にに記事の新規投稿/更新・コメント・Star等の活動を行ったメンバー数です。
   * @type {number}
   * @memberof TeamStats
   */
  weekly_active_users: number;
  /**
   * 過去30日間以内にに記事の新規投稿/更新・コメント・Star等の活動を行ったメンバー数です。
   * @type {number}
   * @memberof TeamStats
   */
  monthly_active_users: number;
}
