/* tslint:disable */
/* eslint-disable */
/**
 * esa API v1
 * チームのナレッジ共有サービス[esa.io](https://esa.io/)のAPI v1の仕様書
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Stargazer } from "./stargazer";
import { User } from "./user";

/**
 * ユーザが作成したコメントを表します。
 * @export
 * @interface Comment
 */
export interface Comment {
  /**
   * コメントを一意に識別するIDです
   * @type {number}
   * @memberof Comment
   */
  id: number;
  /**
   * Markdownで書かれたコメントの本文です
   * @type {string}
   * @memberof Comment
   */
  body_md: string;
  /**
   * HTMLに変換されたコメントの本文です
   * @type {string}
   * @memberof Comment
   */
  body_html: string;
  /**
   * コメントが作成された日時です
   * @type {string}
   * @memberof Comment
   */
  created_at: string;
  /**
   * コメントが更新された日時です
   * @type {string}
   * @memberof Comment
   */
  updated_at: string;
  /**
   *
   * @type {number}
   * @memberof Comment
   */
  post_number: number;
  /**
   * コメントのpermalinkです
   * @type {string}
   * @memberof Comment
   */
  url: string;
  /**
   * コメントを作成したユーザです
   * @type {User}
   * @memberof Comment
   */
  created_by: User;
  /**
   * コメントにStarをしている人数を表します
   * @type {number}
   * @memberof Comment
   */
  stargazers_count: number;
  /**
   * ユーザーがコメントをStarしているかどうかを表します
   * @type {boolean}
   * @memberof Comment
   */
  star: boolean;
  /**
   * コメントにStarをしたユーザ一覧です
   * @type {Array<Stargazer>}
   * @memberof Comment
   */
  stargazers?: Array<Stargazer>;
}
