/* tslint:disable */
/* eslint-disable */
/**
 * esa API v1
 * チームのナレッジ共有サービス[esa.io](https://esa.io/)のAPI v1の仕様書
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * チームのメンバーを表します。
 * @export
 * @interface Member
 */
export interface Member {
  /**
   * 自分自身であるかどうかのフラグです。
   * @type {boolean}
   * @memberof Member
   */
  myself: boolean;
  /**
   * メンバーの名前です
   * @type {string}
   * @memberof Member
   */
  name: string;
  /**
   * メンバーのスクリーンネームです
   * @type {string}
   * @memberof Member
   */
  screen_name: string;
  /**
   * メンバーのアイコンのURLです
   * @type {string}
   * @memberof Member
   */
  icon: string;
  /**
   * メンバーのロール(owner, member)です。
   * @type {string}
   * @memberof Member
   */
  role: MemberRoleEnum;
  /**
   * チーム内でメンバーが作成した記事数です
   * @type {number}
   * @memberof Member
   */
  posts_count: number;
  /**
   * チームにメンバーが参加した日時です
   * @type {string}
   * @memberof Member
   */
  joined_at: string;
  /**
   * チームにメンバーがアクセスした最後の日時です
   * @type {string}
   * @memberof Member
   */
  last_accessed_at: string;
  /**
   * メンバーのemailです。このフィールドは team の owner だけが取得可能です
   * @type {string}
   * @memberof Member
   */
  email?: string;
}

/**
 * @export
 * @enum {string}
 */
export enum MemberRoleEnum {
  Owner = "owner",
  Member = "member",
}
