/* tslint:disable */
/* eslint-disable */
/**
 * esa API v1
 * チームのナレッジ共有サービス[esa.io](https://esa.io/)のAPI v1の仕様書
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 外部公開のURLです。外部公開が有効になっていない場合`null`になります。
 * @export
 * @interface SharingUrls
 */
export interface SharingUrls {
  /**
   * HTMLページのURLです。
   * @type {string}
   * @memberof SharingUrls
   */
  html: string;
  /**
   * スライドページのURLです。
   * @type {string}
   * @memberof SharingUrls
   */
  slides: string;
}
