/* tslint:disable */
/* eslint-disable */
/**
 * esa API v1
 * チームのナレッジ共有サービス[esa.io](https://esa.io/)のAPI v1の仕様書
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * esa上で所属しているチームを表します。
 * @export
 * @interface Team
 */
export interface Team {
  /**
   * チームを特定するための一意なIDです。サブドメインになります。
   * @type {string}
   * @memberof Team
   */
  name: string;
  /**
   * チームの公開範囲です。closed: \"チームメンバーだけが情報にアクセスできます。open: \"ShipItされた記事はインターネット上に公開されます。\"
   * @type {string}
   * @memberof Team
   */
  privacy: TeamPrivacyEnum;
  /**
   * チームの説明です。登録がない場合には空文字列(\"\")になります。
   * @type {string}
   * @memberof Team
   */
  description: string;
  /**
   * チームのアイコンです。
   * @type {string}
   * @memberof Team
   */
  icon: string;
  /**
   * チームのURLです。
   * @type {string}
   * @memberof Team
   */
  url: string;
}

/**
 * @export
 * @enum {string}
 */
export enum TeamPrivacyEnum {
  Closed = "closed",
  Open = "open",
}
