/* tslint:disable */
/* eslint-disable */
/**
 * esa API v1
 * チームのナレッジ共有サービス[esa.io](https://esa.io/)のAPI v1の仕様書
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 記事を作成したユーザ、記事を最後に更新したユーザ、コメントを作成したユーザ、スターをしたユーザなどを表します。
 * @export
 * @interface User
 */
export interface User {
  /**
   * 自分自身であるかどうかのフラグです。
   * @type {boolean}
   * @memberof User
   */
  myself: boolean;
  /**
   * ユーザ名です。
   * @type {string}
   * @memberof User
   */
  name: string;
  /**
   * ユーザを一意に識別するIDです。
   * @type {string}
   * @memberof User
   */
  screen_name: string;
  /**
   * ユーザのアイコンのURLです。
   * @type {string}
   * @memberof User
   */
  icon: string;
}
